name: CI CD Proccess SIPPP Anggaran

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-ci-cd:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name : git pull
      run : git pull
    - name: Install Composer
      run: composer update
    - name : run migration
      run : yes | php artisan migrate
    - name : run seeder
      run : yes | php artisan db:seed
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 bootstrap/cache
    - name: Directory Permissions
      run: chmod -R 777 storage
   
