name: CI CD Proccess SIPPP Anggaran

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      uses: appleboy/ssh-action@master

      with:

        host: 178.16.142.192

        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICVilz6pqL4lWrvFuBUJZoKcigSjcHmmpIMZQqqsOpAs newustechnology@gmail.com

        username: root

        script: |

          cd /home/sippp-puprtubabakab-anggaran/htdocs/anggaran.sippp-puprtubabakab.com

          git checkout -f

          git pull
