name: CI CD Proccess SIPPP Anggaran

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      run: |

          cd /home/sippp-puprtubabakab-anggaran/htdocs/anggaran.sippp-puprtubabakab.com

          git checkout -f
          
          git pull
    - name: Install dependencies
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
      run: |
        composer update
    - run : php artisan migrate
    - run : systemctl restart nginx
